services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: healthcheck_app
    ports:
      - 5432:5432

  app: 
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=healthcheck_app
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - PORT=8080
    depends_on:
      - postgres